[project]
name = "simple RAG"
version = "0.1.0"
description = "Simple RAG – Learning Playground"
readme = "README.md"
requires-python = ">= 3.12"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
